### PR TITLE
Add ability to access current state

### PR DESCRIPTION
**Pull request by jordond**
I have come across some use-cases where I require to know the current state of Chameleon.  So I have added a variable and its accessor.  I have also added a listener so the developer can react upon state changes.

I updated the sample app to include my changes.

I have also added some extension functions I find useful.  If you would like me to remove them from this PR let me know, or I can add them to the `Chameleon` class instead of the `ChameleonExt.kt`.

### CODE REVIEW

**Comment by sangcomz** [comment]
@jordond 
I think it is very good Pull Request :smile:

One question is, is there an intention that the initial value of the currentState value is EMPTY?
Would it be strange to return a null value or return a new State value?

 thank you!!

**Comment by jordond** [comment]
You're right, I didn't really think about it I just chose EMPTY.  I suppose I could create another attribute, something like `defaultState`.  I'll work on something shortly.

**Comment by jordond** [comment]
I have added two things.

First being a new state called `NONE`, I figured it was better than `null`, and if it's set Chameleon won't do anything.

Second I added a new attribute `defaultState`.  I'm not sure how much I love the approach of using an `Int` enum, but I think it is fine.  However if you don't like that approach, I'm open to an alternative, or can just axe that idea.

I've also updated the README with examples (and a typo or two).

**Comment by jordond** [comment]
Actually thinking about it.  `NONE` and `CONTENT` are essentially the same thing...  Thoughts on removing the `NONE` and setting it to `CONTENT`?

**Comment by sangcomz** [comment]
I agree that the `NONE` state is better than `null`!

I think the difference between `NONE` and `CONTENT` is that the `CONTENT` can be called with the showState function, but the `NONE` state can not be called with the showState function.

 So if someone accidentally calls showState (STATE.NONE), I think we should figure out what to do!
When I think about it briefly....
- Error occurred
- Change view visibility to gone

Do you have any better ideas? Or is there another opinion?

**Comment by jordond** [comment]
I don't think throwing an error on `showState(STATE.NONE)` is ideal, I like the idea of setting the visibility to `GONE`.  

If we go that route, we would probably want to change `stateFromInt(it.getInt(R.styleable.Chameleon_defaultState, -1))` to have a default value of 5 - `STATE.CONTENT`, instead of -1.  So that the view doesn't hide by default, but rather just show the content.

Would probably also want to change the ordering/int values so that the `else` branch goes to `STATE.CONTENT`, for an easier developer experience.

Thoughts? (that make sense?)

**Comment by sangcomz** [comment]
sorry, I don't understand exactly

You mean, the default value is STATE.CONTENT? So you don't use NONE status?

Could you explain it once again, if possible?

**Comment by jordond** [comment]
If we make it so that `STATE.NONE` will set the view's visibility to `GONE`, then we shouldn't make the _default value_ for `defaultState` set to `STATE.NONE`.  Because their view will be hidden by default.  I think setting the _default value_ to `STATE.CONTENT` would be better.  As their view will be visible, and if they need to hide it they can set it to `STATE.NONE`.

I'll work on the sample shortly, and push it.

**Comment by sangcomz** [comment]
Thank you so much for your explanation, now I understand!

The default value is a matter of concern, but I think we can improve it in the future, and I do not know what better yet. But I think it will be OK to `CONTENT`.

Thanks!

**Pull request merged**
